services:
  db:
    image: postgres:17-alpine
    container_name: cert_postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    ports:
      - "${DB_PORT:-6542}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME:-cert}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-journal_school}" ]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7-alpine
    container_name: cert_redis_cache
    restart: always
    ports:
      - "${REDIS_HOST_PORT:-6379}:${REDIS_PORT:-6379}"
    command: redis-server --port ${REDIS_PORT:-6379} --requirepass ${REDIS_PASSWORD:-redis}
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-p", "${REDIS_PORT:-6379}", "-a", "${REDIS_PASSWORD:-redis}", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
  service:
    container_name: cert_backend
    image: backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT:-9090}:9090"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${DB_NAME:-cert}
      - SPRING_DATASOURCE_USERNAME=${DB_USER:-postgres}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD:-postgres}
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=${REDIS_PORT:-6379}
      - SPRING_DATA_REDIS_PASSWORD=${REDIS_PASSWORD:-redis}
      - SERVER_PORT=9090
volumes:
  postgres_data:
  redis_data: