openapi: 3.0.3
info:
  title: API для CertificationAPP PetrSU
  version: 1.0.0
servers:
  - url: /api/v1

security:
  - CookieAuth: []

paths:
  /auth/mobile/register:
    $ref: './paths/auth/mobile/register.yaml'

  /auth/mobile/login:
    $ref: './paths/auth/mobile/login.yaml'

  /auth/mobile/logout:
    $ref: './paths/auth/mobile/logout.yaml'

  /auth/mobile/refresh:
    $ref: './paths/auth/mobile/refresh.yaml'

  /auth/mobile/activate:
    $ref: './paths/auth/mobile/activate.yaml'

  /auth/mobile/activate/verify:
    $ref: './paths/auth/mobile/activate_verify.yaml'

  /auth/mobile/activate/resend:
    $ref: './paths/auth/mobile/resend_activation.yaml'

  /auth/mobile/reset-password:
    $ref: './paths/auth/mobile/reset_password.yaml'

  /auth/mobile/forgot-password:
    $ref: './paths/auth/mobile/forgot_password.yaml'

  /auth/mobile/reset-password/verify:
    $ref: './paths/auth/mobile/reset_password_verify.yaml'


