spring:
  servlet:
    multipart:
      max-file-size: ${MULTIPART_MAX_FILE_SIZE:10MB}
      max-request-size: ${MULTIPART_MAX_REQUEST_SIZE:10MB}
  config:
    import: optional:file:.env[.properties]
  application:
    name: ${APP_NAME:Certification Server}
    url: ${APP_URL:http://localhost:8080}
  mvc:
    servlet:
      path: /api/v1
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:6542/cert}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:redis}
  kafka:
    mail:
      topic: ${KAFKA_MAIL_SEND_TOPIC}
      group-id: ${KAFKA_MAIL_SEND_CONSUMER_GROUP}
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    properties:
      security.protocol: SASL_PLAINTEXT
      sasl.mechanism: PLAIN
      sasl.jaas.config: >-
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="${KAFKA_ADMIN_USERNAME:admin}"
        password="${KAFKA_ADMIN_PASSWORD:admin}";
    consumer:
      group-id: ${KAFKA_MAIL_SEND_CONSUMER_GROUP:mail-service}

email:
  from: ${EMAIL_FROM:onboarding@resend.dev}

ttl:
  activation: 15m
  password-reset: 15m
  session: 30d
resend:
  api-key: ${RESEND_API_KEY}

app:
  name: ${APP_NAME:Certification Server}
  url: ${APP_URL:http://localhost:8080}

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    org.springframework.security: ${LOG_LEVEL_SECURITY:INFO}
    org.springframework.security.web: ${LOG_LEVEL_SECURITY_WEB:INFO}
    io.lettuce.core: DEBUG
    io.lettuce.core.protocol: DEBUG
    org.springframework.data.redis: DEBUG
    org.springframework.web: ${LOG_LEVEL_WEB:INFO}
    ru.cert.certificationserver: ${LOG_LEVEL_APP:DEBUG}
